import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "lilgnars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          {/* Defina o favicon personalizado aqui */}
          <link rel="icon" href="app/gnar.png" />
        </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
